//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakirovTranspComp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int price { get; set; }
        public string car { get; set; }
        public int user { get; set; }
    
        public virtual Arend Arend { get; set; }
        public virtual Client Client { get; set; }
        public virtual Moving Moving { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual Transportation Transportation { get; set; }
    }
}
