//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakirovTranspComp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersOrders
    {
        public string UserFIO { get; set; }
        public string Contact { get; set; }
        public string Car { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
    }
}
