//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakirovTranspComp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string fio { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Client Client { get; set; }
        public virtual Drivers Drivers { get; set; }
    }
}
